### ISSUE TITLE
Member Account securityhub finding aren't getting into s3 bucket

### ISSUE THREAD

**Issue by arunreddy00** [aws-samples/aws-security-hub-findings-export#2]
Hlo AWS,
Securityhub findings aren't present in Master account's S3 bucket, After deploying provided yaml file in cloudformation.

**Comment by farside5** [comment]
Hi arunreddy00,  the most likely cause of this issue is that member accounts are not sending findings to the delegated admin account.  You can either [add member accounts that belong to an organization](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-accounts-orgs.html) or [add member accounts by invitation](https://docs.aws.amazon.com/securityhub/latest/userguide/account-management-manual.html).

**Comment by farside5** [comment]
Merged to issue #4.
