### ISSUE TITLE
Member Account securityhub finding aren't getting into s3 bucket

### ISSUE THREAD

**Issue by jyoti-singh1808** [aws-samples/aws-security-hub-findings-export#4]
I dont see any logs of the member accounts logs into s3 bucket. 

Also how should i store this s3 bucket in different account and run this script in master account and change the arn of s3 bucket and store all the logs in that bucket. Is it possible?

**Comment by farside5** [comment]
Hi jyoti-singh1808,  the most likely cause of your issue is that member accounts are not sending findings to the delegated admin account.  You can either [add member accounts that belong to an organization](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-accounts-orgs.html) or [add member accounts by invitation](https://docs.aws.amazon.com/securityhub/latest/userguide/account-management-manual.html).

at the time of this solution, Security Hub findings are not aggregated cross-region.  You can modify the [securityhub_export.yml](https://github.com/aws-samples/aws-security-hub-findings-export/blob/master/securityhub_export.yml) to achieve this.  When you deploy to a different region, you only need to create kinesis delivery stream to output findings to your central bucket.

Alternatively Security Hub announced [cross-Region support](https://aws.amazon.com/about-aws/whats-new/2021/10/aws-security-hub-cross-region-security-posture/) on 10/20/2021.  You can aggregate findings cross Region, then export the aggregated findings in the Security Hub delegated admin account.
